// <auto-generated />
using System;
using CorrecolTest.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CorrecolTest.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CorrecolDbContext))]
    [Migration("20260924054733_AddCatalogActive")]
    partial class AddCatalogActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CorrecolTest.Domain.Entities.Ciudad", b =>
                {
                    b.Property<int>("Codigo")
                        .HasColumnType("int")
                        .HasColumnName("DvsPltColCodigoDane");

                    b.Property<bool>("Active")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DepartamentoCodigo")
                        .HasColumnType("int")
                        .HasColumnName("DvsPltColDptColCodigoDane");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DvsPltColNombreMunicipio");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Codigo");

                    b.HasIndex("DepartamentoCodigo");

                    b.ToTable("DivisionPoliticaColombia", (string)null);
                });

            modelBuilder.Entity("CorrecolTest.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClnId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("CiudadCodigo")
                        .HasColumnType("int")
                        .HasColumnName("ClnDvsPltColCodigoDane");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("DepartamentoCodigo")
                        .HasColumnType("int")
                        .HasColumnName("ClnDptColCodigoDane");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("ClnNumeroIdentificacion");

                    b.Property<short>("PaisCodigo")
                        .HasColumnType("smallint")
                        .HasColumnName("ClnPaisCodigo");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ClnRazonSocial");

                    b.Property<short>("TipoIdentificacion")
                        .HasColumnType("smallint")
                        .HasColumnName("ClnTpoIdnId");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("PaisCodigo");

                    b.HasIndex("CiudadCodigo", "DepartamentoCodigo");

                    b.HasIndex("DepartamentoCodigo", "PaisCodigo");

                    b.HasIndex("TipoIdentificacion", "NumeroIdentificacion")
                        .IsUnique();

                    b.ToTable("Cliente", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cliente_CiudadDepartamento", "[ClnDvsPltColCodigoDane] IS NULL OR [ClnDptColCodigoDane] IS NOT NULL");

                            t.HasCheckConstraint("CK_Cliente_Identificacion", "LEN(LTRIM(RTRIM([ClnNumeroIdentificacion]))) > 0");

                            t.HasCheckConstraint("CK_Cliente_RazonSocial", "LEN(LTRIM(RTRIM([ClnRazonSocial]))) > 0");

                            t.HasCheckConstraint("CK_Cliente_TipoIdentificacion", "[ClnTpoIdnId] IN (1,2,3,4,5)");
                        });
                });

            modelBuilder.Entity("CorrecolTest.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("Codigo")
                        .HasColumnType("int")
                        .HasColumnName("DptColCodigoDane");

                    b.Property<bool>("Active")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DptColNombredelDepartamento");

                    b.Property<short>("PaisCodigo")
                        .HasColumnType("smallint")
                        .HasColumnName("DptColPaisCodigo");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Codigo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("PaisCodigo");

                    b.ToTable("DepartamentosColombia", (string)null);
                });

            modelBuilder.Entity("CorrecolTest.Domain.Entities.Pais", b =>
                {
                    b.Property<short>("Codigo")
                        .HasColumnType("smallint")
                        .HasColumnName("PaisCodigo");

                    b.Property<bool>("Active")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Capital")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PaisCapital");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Iso1")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("PaisIso1");

                    b.Property<string>("Iso2")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("PaisIso2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PaisNombre");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Codigo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Pais", (string)null);
                });

            modelBuilder.Entity("CorrecolTest.Domain.Entities.Ciudad", b =>
                {
                    b.HasOne("CorrecolTest.Domain.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("CorrecolTest.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("CorrecolTest.Domain.Entities.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorrecolTest.Domain.Entities.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadCodigo", "DepartamentoCodigo")
                        .HasPrincipalKey("Codigo", "DepartamentoCodigo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CorrecolTest.Domain.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoCodigo", "PaisCodigo")
                        .HasPrincipalKey("Codigo", "PaisCodigo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ciudad");

                    b.Navigation("Departamento");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("CorrecolTest.Domain.Entities.Departamento", b =>
                {
                    b.HasOne("CorrecolTest.Domain.Entities.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pais");
                });
#pragma warning restore 612, 618
        }
    }
}
